services:
  dashboard:
    build:
      context: .
    image: my-dashboardkdv:local
    container_name: my-dashboardkdv-dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
